FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "--headless", "--driver", "Chrome", "--html=report.html", "--self-contained-html", "tests/test_example.py"]