# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_test1(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(1) > .font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(3) > .font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(4) > .font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(7) > .font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".xl\\3A border-2:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .hidden > .capitalize").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-3:nth-child(2) > .hidden > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").send_keys("zeraa")
    self.driver.find_element(By.CSS_SELECTOR, ".absolute path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".absolute path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".nsm7Bb-HzV7m-LgbsSe-MJoBVe").click()
    self.vars["win7714"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win7714"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
