version: '3.4'

services:
  frontend:
    build: 
      context : .
      dockerfile : Dockerfile_front
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./sanity-backend
      dockerfile: Dockerfile_back
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  selenium:
    image: selenium/standalone-chrome:latest
    # networks:
    #   - frontend
    #   - backend