# FROM node:lts-alpine
FROM node:latest

# ENV NODE_ENV=production

WORKDIR /usr/src/app

ADD package.json /usr/src/app/package.json

# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# COPY package*.json ./
# COPY . /usr/src/app/

COPY package*.json ./
COPY .next /app/.next

RUN npm install 
# ADD . /usr/src/app

#--production --silent && mv node_modules ../
# COPY . .
EXPOSE 3000

ENV REACT_APP_BACKEND_URL=http://localhost:5000

CMD ["npm", "start"]

