version: '3.4'

services:
  sanitybackend:
    image: sanitybackend
    build:
      context: sanity-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "package.json"]
